name: Publish GH Pages
on:
  workflow_run:
    workflows: [Publish Package to NPM]
    types:
      - completed
    branches:
      - main
      - next
      - beta
      - alpha
      - '[0-9]+.x'
  workflow_dispatch:

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: build
        run: |
          pnpm install
          pnpm build-storybook
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static