name: Publish Package to npmjs
on:
  push:
    branches:
      - main
    paths:
      - .changeset/**/*

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: stage publish
        run: |
          pnpm install
          pnpm ci:version
          pnpm install
          pnpm build

      - name: check in changes
        run: |
          git config user.name github-actions[bot]
          git add .changeset pnpm-lock.yaml package.json CHANGELOG.md
          git commit -m "chore: bump version"
          git push

      - name: publish
        run: |
          pnpm ci:publish
